schema = 1

[[profiles]]
id = "steelseries.aerox9"
path = "steelseries.aerox9.toml"
sha256 = "0abbc78f18c981cc4d2691a9550c660718052d960583e1d00177603adc256486"

[[profiles.matches]]
transport = "usb-hid"
vendor_id = 0x1038
product_id = 0x1858

[[profiles.matches]]
transport = "usb-hid"
vendor_id = 0x1038
product_id = 0x185A
